name: Virtual Lab Setup Workflow

on:
  push:
    branches:
      - main

jobs:
  display_setup_guide:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display Virtual Lab Setup Guide
      run: cat VIRTUAL_LAB_SETUP.md
